// GENERATED by scripts/build-gallery.mjs — do not edit by hand.
// Add or remove images in albums/ and let the GitHub Action rebuild this file.
window.GALLERY = {
  "ids": [
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11
  ],
  "RATIO": {
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 1,
    "5": 1,
    "6": 0.677143,
    "7": 1,
    "8": 0.707143,
    "9": 1,
    "10": 0.697857,
    "11": 1
  },
  "CAT": {
    "1": "digital",
    "2": "mixed",
    "3": "digital",
    "4": "mixed",
    "5": "digital",
    "6": "mixed",
    "7": "digital",
    "8": "mixed",
    "9": "digital",
    "10": "mixed",
    "11": "mixed"
  },
  "SRC": {
    "1": "assets/full/digital-001-artwork-01.jpg",
    "2": "assets/full/mixed-002-artwork-02.jpg",
    "3": "assets/full/digital-003-artwork-03.jpg",
    "4": "assets/full/mixed-005-artwork-05.jpg",
    "5": "assets/full/digital-004-artwork-04.jpg",
    "6": "assets/full/mixed-007-artwork-07.jpg",
    "7": "assets/full/digital-006-artwork-06.jpg",
    "8": "assets/full/mixed-008-artwork-08.jpg",
    "9": "assets/full/digital-009-artwork-09.jpg",
    "10": "assets/full/mixed-010-artwork-10.jpg",
    "11": "assets/full/mixed-011-artwork-11.jpg"
  },
  "THUMB": {
    "1": "assets/thumb/digital-001-artwork-01.jpg",
    "2": "assets/thumb/mixed-002-artwork-02.jpg",
    "3": "assets/thumb/digital-003-artwork-03.jpg",
    "4": "assets/thumb/mixed-005-artwork-05.jpg",
    "5": "assets/thumb/digital-004-artwork-04.jpg",
    "6": "assets/thumb/mixed-007-artwork-07.jpg",
    "7": "assets/thumb/digital-006-artwork-06.jpg",
    "8": "assets/thumb/mixed-008-artwork-08.jpg",
    "9": "assets/thumb/digital-009-artwork-09.jpg",
    "10": "assets/thumb/mixed-010-artwork-10.jpg",
    "11": "assets/thumb/mixed-011-artwork-11.jpg"
  },
  "TITLE": {
    "1": "Artwork 01",
    "2": "Artwork 02",
    "3": "Artwork 03",
    "4": "Artwork 05",
    "5": "Artwork 04",
    "6": "Artwork 07",
    "7": "Artwork 06",
    "8": "Artwork 08",
    "9": "Artwork 09",
    "10": "Artwork 10",
    "11": "Artwork 11"
  },
  "DATE": {
    "1": "",
    "2": "",
    "3": "",
    "4": "",
    "5": "",
    "6": "",
    "7": "",
    "8": "",
    "9": "",
    "10": "",
    "11": ""
  },
  "ALT": {
    "1": "Artwork 01 — digital work by Lukas Meyer",
    "2": "Artwork 02 — mixed media work by Lukas Meyer",
    "3": "Artwork 03 — digital work by Lukas Meyer",
    "4": "Artwork 05 — mixed media work by Lukas Meyer",
    "5": "Artwork 04 — digital work by Lukas Meyer",
    "6": "Artwork 07 — mixed media work by Lukas Meyer",
    "7": "Artwork 06 — digital work by Lukas Meyer",
    "8": "Artwork 08 — mixed media work by Lukas Meyer",
    "9": "Artwork 09 — digital work by Lukas Meyer",
    "10": "Artwork 10 — mixed media work by Lukas Meyer",
    "11": "Artwork 11 — mixed media work by Lukas Meyer"
  },
  "SUBS": {
    "digital": {
      "1_0": 5,
      "1_1": 7,
      "3_0": 9,
      "3_1": 1,
      "5_0": 9,
      "5_1": 3,
      "7_0": 1,
      "7_1": 1,
      "9_0": 3,
      "9_1": 3,
      "10_0": 5,
      "10_1": 7
    },
    "mixed": {
      "0_0": 4,
      "0_1": 6,
      "2_0": 8,
      "2_1": 8,
      "4_0": 10,
      "4_1": 2,
      "6_0": 10,
      "6_1": 2,
      "8_0": 4,
      "8_1": 2
    }
  },
  "B_ROW": 2,
  "banner": [
    "assets/full/digital-001-artwork-01.jpg",
    "assets/full/digital-009-artwork-09.jpg"
  ],
  "firstLook": "assets/full/mixed-005-artwork-05.jpg",
  "filters": [
    "all",
    "digital",
    "mixed"
  ],
  "generated": "2026-08-15"
};
