#!/usr/bin/env node
// Produces the single-file preview from the real site, so the two can never drift apart.
// Everything is inlined as base64 — one file to open on a phone, nothing to upload.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const asData = async (p, mime) =>
  `data:${mime};base64,${(await readFile(path.join(ROOT, p))).toString('base64')}`;

let html = await readFile(path.join(ROOT, 'index.html'), 'utf8');
const data = await readFile(path.join(ROOT, 'gallery-data.js'), 'utf8');

// fold the generated data into the page's own script
html = html.replace('<script src="gallery-data.js"></script>\n<script>\n', '<script>\n' + data + '\n');

// then swap every file reference for its contents
const g = {};
new Function('window', data)(g);
const G = g.GALLERY;
const seen = new Map();
for(const id of G.ids){
  for(const p of [G.SRC[id], G.THUMB[id]]){
    if(!seen.has(p)) seen.set(p, await asData(p, 'image/jpeg'));
  }
}
for(const [p, uri] of seen){
  html = html.split('"' + p + '"').join('"' + uri + '"');
  html = html.split("'" + p + "'").join("'" + uri + "'");
}
html = html.replace(/href="favicon\.png"/g, `href="${await asData('favicon.png','image/png')}"`);
html = html.replace(/content="share-preview\.jpg"/g, 'content=""');
html = html.replace('<title>Lukas Meyer — portfolio</title>',
                    '<title>Lukas Meyer — portfolio (preview)</title>');
html = html.replace('<html lang="en">',
  '<!-- PREVIEW: generated by scripts/make-preview.mjs. Everything inlined; do not upload. -->\n<html lang="en">');

await writeFile(path.join(ROOT, 'site-preview-DO-NOT-UPLOAD.html'), html, 'utf8');
console.log('preview written:', (Buffer.byteLength(html)/1024/1024).toFixed(2), 'MB');
